<?php

namespace DoctrineProxies\__CG__\Concrete\Package\CommunityStore\Src\CommunityStore\Order;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Order extends \Concrete\Package\CommunityStore\Src\CommunityStore\Order\Order implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'oID', 'cID', 'oDate', 'pmID', 'pmName', 'smName', 'sInstructions', 'oShippingTotal', 'oTax', 'oTaxIncluded', 'oTaxName', 'oTotal', 'transactionReference', 'oPaid', 'oPaidByUID', 'oCancelled', 'oCancelledByUID', 'oRefunded', 'oRefundedByUID', 'oRefundReason', 'externalPaymentRequested', 'orderItems');
        }

        return array('__isInitialized__', 'oID', 'cID', 'oDate', 'pmID', 'pmName', 'smName', 'sInstructions', 'oShippingTotal', 'oTax', 'oTaxIncluded', 'oTaxName', 'oTotal', 'transactionReference', 'oPaid', 'oPaidByUID', 'oCancelled', 'oCancelledByUID', 'oRefunded', 'oRefundedByUID', 'oRefundReason', 'externalPaymentRequested', 'orderItems');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Order $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getOrderItems()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderItems', array());

        return parent::getOrderItems();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerID($cID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerID', array($cID));

        return parent::setCustomerID($cID);
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($oDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', array($oDate));

        return parent::setDate($oDate);
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentMethodName($pmName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentMethodName', array($pmName));

        return parent::setPaymentMethodName($pmName);
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentMethodID($pmID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentMethodID', array($pmID));

        return parent::setPaymentMethodID($pmID);
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingMethodName($smName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingMethodName', array($smName));

        return parent::setShippingMethodName($smName);
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingInstructions($sInstructions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingInstructions', array($sInstructions));

        return parent::setShippingInstructions($sInstructions);
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingTotal($shippingTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingTotal', array($shippingTotal));

        return parent::setShippingTotal($shippingTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function setTaxTotal($taxTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaxTotal', array($taxTotal));

        return parent::setTaxTotal($taxTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function setTaxIncluded($taxIncluded)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaxIncluded', array($taxIncluded));

        return parent::setTaxIncluded($taxIncluded);
    }

    /**
     * {@inheritDoc}
     */
    public function setTaxLabels($taxLabels)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaxLabels', array($taxLabels));

        return parent::setTaxLabels($taxLabels);
    }

    /**
     * {@inheritDoc}
     */
    public function setTotal($total)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotal', array($total));

        return parent::setTotal($total);
    }

    /**
     * {@inheritDoc}
     */
    public function setTransactionReference($transactionReference)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTransactionReference', array($transactionReference));

        return parent::setTransactionReference($transactionReference);
    }

    /**
     * {@inheritDoc}
     */
    public function saveTransactionReference($transactionReference)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'saveTransactionReference', array($transactionReference));

        return parent::saveTransactionReference($transactionReference);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaid', array());

        return parent::getPaid();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaid($oPaid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaid', array($oPaid));

        return parent::setPaid($oPaid);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaidByUID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaidByUID', array());

        return parent::getPaidByUID();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaidByUID($oPaidByUID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaidByUID', array($oPaidByUID));

        return parent::setPaidByUID($oPaidByUID);
    }

    /**
     * {@inheritDoc}
     */
    public function getCancelled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCancelled', array());

        return parent::getCancelled();
    }

    /**
     * {@inheritDoc}
     */
    public function setCancelled($oCancelled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCancelled', array($oCancelled));

        return parent::setCancelled($oCancelled);
    }

    /**
     * {@inheritDoc}
     */
    public function getCancelledByUID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCancelledByUID', array());

        return parent::getCancelledByUID();
    }

    /**
     * {@inheritDoc}
     */
    public function setCancelledByUID($oCancelledByUID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCancelledByUID', array($oCancelledByUID));

        return parent::setCancelledByUID($oCancelledByUID);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefunded()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefunded', array());

        return parent::getRefunded();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefunded($oRefunded)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefunded', array($oRefunded));

        return parent::setRefunded($oRefunded);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefundedByUID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefundedByUID', array());

        return parent::getRefundedByUID();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefundedByUID($oRefundedByUID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefundedByUID', array($oRefundedByUID));

        return parent::setRefundedByUID($oRefundedByUID);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefundReason()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefundReason', array());

        return parent::getRefundReason();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefundReason($oRefundReason)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefundReason', array($oRefundReason));

        return parent::setRefundReason($oRefundReason);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderID', array());

        return parent::getOrderID();
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerID', array());

        return parent::getCustomerID();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderDate', array());

        return parent::getOrderDate();
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentMethodID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentMethodID', array());

        return parent::getPaymentMethodID();
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentMethodName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentMethodName', array());

        return parent::getPaymentMethodName();
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingMethodName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingMethodName', array());

        return parent::getShippingMethodName();
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingInstructions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingInstructions', array());

        return parent::getShippingInstructions();
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingTotal', array());

        return parent::getShippingTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function getTaxes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaxes', array());

        return parent::getTaxes();
    }

    /**
     * {@inheritDoc}
     */
    public function getTaxTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaxTotal', array());

        return parent::getTaxTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function getIncludedTaxTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIncludedTaxTotal', array());

        return parent::getIncludedTaxTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function getTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotal', array());

        return parent::getTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function getSubTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubTotal', array());

        return parent::getSubTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function getTransactionReference()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransactionReference', array());

        return parent::getTransactionReference();
    }

    /**
     * {@inheritDoc}
     */
    public function getExternalPaymentRequested()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExternalPaymentRequested', array());

        return parent::getExternalPaymentRequested();
    }

    /**
     * {@inheritDoc}
     */
    public function setExternalPaymentRequested($bool)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExternalPaymentRequested', array($bool));

        return parent::setExternalPaymentRequested($bool);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomersMostRecentOrderByCID($cID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomersMostRecentOrderByCID', array($cID));

        return parent::getCustomersMostRecentOrderByCID($cID);
    }

    /**
     * {@inheritDoc}
     */
    public function addCustomerAddress($customer = NULL, $includeShipping = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCustomerAddress', array($customer, $includeShipping));

        return parent::addCustomerAddress($customer, $includeShipping);
    }

    /**
     * {@inheritDoc}
     */
    public function completeOrder($transactionReference = NULL, $sameRequest = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'completeOrder', array($transactionReference, $sameRequest));

        return parent::completeOrder($transactionReference, $sameRequest);
    }

    /**
     * {@inheritDoc}
     */
    public function completePayment($sameRequest = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'completePayment', array($sameRequest));

        return parent::completePayment($sameRequest);
    }

    /**
     * {@inheritDoc}
     */
    public function completePostPaymentProcesses($sameRequest = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'completePostPaymentProcesses', array($sameRequest));

        return parent::completePostPaymentProcesses($sameRequest);
    }

    /**
     * {@inheritDoc}
     */
    public function sendNotifications()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'sendNotifications', array());

        return parent::sendNotifications();
    }

    /**
     * {@inheritDoc}
     */
    public function sendOrderReceipt($email = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'sendOrderReceipt', array($email));

        return parent::sendOrderReceipt($email);
    }

    /**
     * {@inheritDoc}
     */
    public function addOrderItems($cart, $discountRatio = 1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrderItems', array($cart, $discountRatio));

        return parent::addOrderItems($cart, $discountRatio);
    }

    /**
     * {@inheritDoc}
     */
    public function save()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'save', array());

        return parent::save();
    }

    /**
     * {@inheritDoc}
     */
    public function delete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'delete', array());

        return parent::delete();
    }

    /**
     * {@inheritDoc}
     */
    public function remove()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'remove', array());

        return parent::remove();
    }

    /**
     * {@inheritDoc}
     */
    public function isShippable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isShippable', array());

        return parent::isShippable();
    }

    /**
     * {@inheritDoc}
     */
    public function updateStatus($status = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'updateStatus', array($status));

        return parent::updateStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatusHistory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatusHistory', array());

        return parent::getStatusHistory();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatusHandle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatusHandle', array());

        return parent::getStatusHandle();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttribute($ak, $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttribute', array($ak, $value));

        return parent::setAttribute($ak, $value);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttribute($ak, $displayMode = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttribute', array($ak, $displayMode));

        return parent::getAttribute($ak, $displayMode);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttributeValueObject($ak, $createIfNotFound = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttributeValueObject', array($ak, $createIfNotFound));

        return parent::getAttributeValueObject($ak, $createIfNotFound);
    }

    /**
     * {@inheritDoc}
     */
    public function addDiscount($discount, $code = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDiscount', array($discount, $code));

        return parent::addDiscount($discount, $code);
    }

    /**
     * {@inheritDoc}
     */
    public function getAppliedDiscounts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAppliedDiscounts', array());

        return parent::getAppliedDiscounts();
    }

    /**
     * {@inheritDoc}
     */
    public function saveOrderChoices($order)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'saveOrderChoices', array($order));

        return parent::saveOrderChoices($order);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressValue($handle, $valuename)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressValue', array($handle, $valuename));

        return parent::getAddressValue($handle, $valuename);
    }

}
