<?php

namespace DoctrineProxies\__CG__\Concrete\Package\CommunityStore\Src\CommunityStore\Product;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \Concrete\Package\CommunityStore\Src\CommunityStore\Product\Product implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'pID', 'cID', 'pName', 'pSKU', 'pDesc', 'pDetail', 'pPrice', 'pSalePrice', 'pCustomerPrice', 'pPriceMaximum', 'pPriceMinimum', 'pPriceSuggestions', 'pFeatured', 'pQty', 'pQtyUnlim', 'pBackOrder', 'pNoQty', 'pTaxClass', 'pTaxable', 'pfID', 'pActive', 'pDateAdded', 'pShippable', 'pWidth', 'pHeight', 'pLength', 'pWeight', 'pNumberItems', 'pCreateUserAccount', 'pAutoCheckout', 'pExclusive', 'pVariations', 'variation', 'locations', 'groups', 'files', 'images', 'userGroups', 'options', 'related');
        }

        return array('__isInitialized__', 'pID', 'cID', 'pName', 'pSKU', 'pDesc', 'pDetail', 'pPrice', 'pSalePrice', 'pCustomerPrice', 'pPriceMaximum', 'pPriceMinimum', 'pPriceSuggestions', 'pFeatured', 'pQty', 'pQtyUnlim', 'pBackOrder', 'pNoQty', 'pTaxClass', 'pTaxable', 'pfID', 'pActive', 'pDateAdded', 'pShippable', 'pWidth', 'pHeight', 'pLength', 'pWeight', 'pNumberItems', 'pCreateUserAccount', 'pAutoCheckout', 'pExclusive', 'pVariations', 'variation', 'locations', 'groups', 'files', 'images', 'userGroups', 'options', 'related');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Product $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * {@inheritDoc}
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());

        parent::__clone();
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getLocations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocations', array());

        return parent::getLocations();
    }

    /**
     * {@inheritDoc}
     */
    public function getGroups()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroups', array());

        return parent::getGroups();
    }

    /**
     * {@inheritDoc}
     */
    public function getFiles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFiles', array());

        return parent::getFiles();
    }

    /**
     * {@inheritDoc}
     */
    public function getImages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImages', array());

        return parent::getImages();
    }

    /**
     * {@inheritDoc}
     */
    public function getUserGroups()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserGroups', array());

        return parent::getUserGroups();
    }

    /**
     * {@inheritDoc}
     */
    public function getOptions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOptions', array());

        return parent::getOptions();
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedProducts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedProducts', array());

        return parent::getRelatedProducts();
    }

    /**
     * {@inheritDoc}
     */
    public function setVariation($variation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVariation', array($variation));

        return parent::setVariation($variation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeVariation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeVariation', array());

        return parent::removeVariation();
    }

    /**
     * {@inheritDoc}
     */
    public function setInitialVariation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInitialVariation', array());

        return parent::setInitialVariation();
    }

    /**
     * {@inheritDoc}
     */
    public function getVariation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVariation', array());

        return parent::getVariation();
    }

    /**
     * {@inheritDoc}
     */
    public function setCollectionID($cID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCollectionID', array($cID));

        return parent::setCollectionID($cID);
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function setSKU($sku)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSKU', array($sku));

        return parent::setSKU($sku);
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function setDetail($detail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDetail', array($detail));

        return parent::setDetail($detail);
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', array($price));

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function setSalePrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalePrice', array($price));

        return parent::setSalePrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerPrice($bool)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerPrice', array($bool));

        return parent::setCustomerPrice($bool);
    }

    /**
     * {@inheritDoc}
     */
    public function getPriceMaximum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriceMaximum', array());

        return parent::getPriceMaximum();
    }

    /**
     * {@inheritDoc}
     */
    public function setPriceMaximum($pPriceMaximum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriceMaximum', array($pPriceMaximum));

        return parent::setPriceMaximum($pPriceMaximum);
    }

    /**
     * {@inheritDoc}
     */
    public function getPriceMinimum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriceMinimum', array());

        return parent::getPriceMinimum();
    }

    /**
     * {@inheritDoc}
     */
    public function setPriceMinimum($pPriceMinimum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriceMinimum', array($pPriceMinimum));

        return parent::setPriceMinimum($pPriceMinimum);
    }

    /**
     * {@inheritDoc}
     */
    public function getPriceSuggestions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriceSuggestions', array());

        return parent::getPriceSuggestions();
    }

    /**
     * {@inheritDoc}
     */
    public function getPriceSuggestionsArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriceSuggestionsArray', array());

        return parent::getPriceSuggestionsArray();
    }

    /**
     * {@inheritDoc}
     */
    public function setPriceSuggestions($priceSuggestions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriceSuggestions', array($priceSuggestions));

        return parent::setPriceSuggestions($priceSuggestions);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsFeatured($bool)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsFeatured', array($bool));

        return parent::setIsFeatured($bool);
    }

    /**
     * {@inheritDoc}
     */
    public function setQty($qty)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQty', array($qty));

        return parent::setQty($qty);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsUnlimited($bool)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsUnlimited', array($bool));

        return parent::setIsUnlimited($bool);
    }

    /**
     * {@inheritDoc}
     */
    public function setAllowBackOrder($bool)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAllowBackOrder', array($bool));

        return parent::setAllowBackOrder($bool);
    }

    /**
     * {@inheritDoc}
     */
    public function setNoQty($bool)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoQty', array($bool));

        return parent::setNoQty($bool);
    }

    /**
     * {@inheritDoc}
     */
    public function setTaxClass($taxClass)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaxClass', array($taxClass));

        return parent::setTaxClass($taxClass);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsTaxable($bool)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsTaxable', array($bool));

        return parent::setIsTaxable($bool);
    }

    /**
     * {@inheritDoc}
     */
    public function setImageID($fID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageID', array($fID));

        return parent::setImageID($fID);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsActive($bool)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsActive', array($bool));

        return parent::setIsActive($bool);
    }

    /**
     * {@inheritDoc}
     */
    public function setDateAdded($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateAdded', array($date));

        return parent::setDateAdded($date);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsShippable($bool)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsShippable', array($bool));

        return parent::setIsShippable($bool);
    }

    /**
     * {@inheritDoc}
     */
    public function setWidth($width)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWidth', array($width));

        return parent::setWidth($width);
    }

    /**
     * {@inheritDoc}
     */
    public function setHeight($height)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeight', array($height));

        return parent::setHeight($height);
    }

    /**
     * {@inheritDoc}
     */
    public function setLength($length)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLength', array($length));

        return parent::setLength($length);
    }

    /**
     * {@inheritDoc}
     */
    public function setWeight($weight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWeight', array($weight));

        return parent::setWeight($weight);
    }

    /**
     * {@inheritDoc}
     */
    public function setNumberItems($number)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumberItems', array($number));

        return parent::setNumberItems($number);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatesUserAccount($bool)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatesUserAccount', array($bool));

        return parent::setCreatesUserAccount($bool);
    }

    /**
     * {@inheritDoc}
     */
    public function setAutoCheckout($bool)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAutoCheckout', array($bool));

        return parent::setAutoCheckout($bool);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsExclusive($bool)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsExclusive', array($bool));

        return parent::setIsExclusive($bool);
    }

    /**
     * {@inheritDoc}
     */
    public function setHasVariations($bool)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHasVariations', array($bool));

        return parent::setHasVariations($bool);
    }

    /**
     * {@inheritDoc}
     */
    public function updateProductQty($qty)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'updateProductQty', array($qty));

        return parent::updateProductQty($qty);
    }

    /**
     * {@inheritDoc}
     */
    public function getID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getID', array());

        return parent::getID();
    }

    /**
     * {@inheritDoc}
     */
    public function setID($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setID', array($id));

        return parent::setID($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function getSKU()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSKU', array());

        return parent::getSKU();
    }

    /**
     * {@inheritDoc}
     */
    public function getPageID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPageID', array());

        return parent::getPageID();
    }

    /**
     * {@inheritDoc}
     */
    public function getDesc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDesc', array());

        return parent::getDesc();
    }

    /**
     * {@inheritDoc}
     */
    public function getDetail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDetail', array());

        return parent::getDetail();
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', array());

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function getFormattedOriginalPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormattedOriginalPrice', array());

        return parent::getFormattedOriginalPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function getFormattedPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormattedPrice', array());

        return parent::getFormattedPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalePrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalePrice', array());

        return parent::getSalePrice();
    }

    /**
     * {@inheritDoc}
     */
    public function getFormattedSalePrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormattedSalePrice', array());

        return parent::getFormattedSalePrice();
    }

    /**
     * {@inheritDoc}
     */
    public function getActivePrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivePrice', array());

        return parent::getActivePrice();
    }

    /**
     * {@inheritDoc}
     */
    public function getFormattedActivePrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormattedActivePrice', array());

        return parent::getFormattedActivePrice();
    }

    /**
     * {@inheritDoc}
     */
    public function getTaxClassID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaxClassID', array());

        return parent::getTaxClassID();
    }

    /**
     * {@inheritDoc}
     */
    public function getTaxClass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaxClass', array());

        return parent::getTaxClass();
    }

    /**
     * {@inheritDoc}
     */
    public function isTaxable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isTaxable', array());

        return parent::isTaxable();
    }

    /**
     * {@inheritDoc}
     */
    public function isFeatured()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isFeatured', array());

        return parent::isFeatured();
    }

    /**
     * {@inheritDoc}
     */
    public function isActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isActive', array());

        return parent::isActive();
    }

    /**
     * {@inheritDoc}
     */
    public function isShippable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isShippable', array());

        return parent::isShippable();
    }

    /**
     * {@inheritDoc}
     */
    public function allowCustomerPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'allowCustomerPrice', array());

        return parent::allowCustomerPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function getDimensions($whl = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDimensions', array($whl));

        return parent::getDimensions($whl);
    }

    /**
     * {@inheritDoc}
     */
    public function getWeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWeight', array());

        return parent::getWeight();
    }

    /**
     * {@inheritDoc}
     */
    public function getNumberItems()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumberItems', array());

        return parent::getNumberItems();
    }

    /**
     * {@inheritDoc}
     */
    public function getImageID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageID', array());

        return parent::getImageID();
    }

    /**
     * {@inheritDoc}
     */
    public function getImageObj()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageObj', array());

        return parent::getImageObj();
    }

    /**
     * {@inheritDoc}
     */
    public function getBaseProductImageID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBaseProductImageID', array());

        return parent::getBaseProductImageID();
    }

    /**
     * {@inheritDoc}
     */
    public function getBaseProductImageObj()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBaseProductImageObj', array());

        return parent::getBaseProductImageObj();
    }

    /**
     * {@inheritDoc}
     */
    public function hasDigitalDownload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasDigitalDownload', array());

        return parent::hasDigitalDownload();
    }

    /**
     * {@inheritDoc}
     */
    public function getDownloadFiles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDownloadFiles', array());

        return parent::getDownloadFiles();
    }

    /**
     * {@inheritDoc}
     */
    public function getDownloadFileObjects()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDownloadFileObjects', array());

        return parent::getDownloadFileObjects();
    }

    /**
     * {@inheritDoc}
     */
    public function createsLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'createsLogin', array());

        return parent::createsLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function allowQuantity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'allowQuantity', array());

        return parent::allowQuantity();
    }

    /**
     * {@inheritDoc}
     */
    public function isExclusive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isExclusive', array());

        return parent::isExclusive();
    }

    /**
     * {@inheritDoc}
     */
    public function hasVariations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasVariations', array());

        return parent::hasVariations();
    }

    /**
     * {@inheritDoc}
     */
    public function isUnlimited()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isUnlimited', array());

        return parent::isUnlimited();
    }

    /**
     * {@inheritDoc}
     */
    public function autoCheckout()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'autoCheckout', array());

        return parent::autoCheckout();
    }

    /**
     * {@inheritDoc}
     */
    public function allowBackOrders()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'allowBackOrders', array());

        return parent::allowBackOrders();
    }

    /**
     * {@inheritDoc}
     */
    public function hasUserGroups()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasUserGroups', array());

        return parent::hasUserGroups();
    }

    /**
     * {@inheritDoc}
     */
    public function getUserGroupIDs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserGroupIDs', array());

        return parent::getUserGroupIDs();
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', array());

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function getImageThumb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageThumb', array());

        return parent::getImageThumb();
    }

    /**
     * {@inheritDoc}
     */
    public function getQty()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQty', array());

        return parent::getQty();
    }

    /**
     * {@inheritDoc}
     */
    public function isSellable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isSellable', array());

        return parent::isSellable();
    }

    /**
     * {@inheritDoc}
     */
    public function getimagesobjects()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getimagesobjects', array());

        return parent::getimagesobjects();
    }

    /**
     * {@inheritDoc}
     */
    public function getLocationPages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocationPages', array());

        return parent::getLocationPages();
    }

    /**
     * {@inheritDoc}
     */
    public function getGroupIDs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroupIDs', array());

        return parent::getGroupIDs();
    }

    /**
     * {@inheritDoc}
     */
    public function getVariations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVariations', array());

        return parent::getVariations();
    }

    /**
     * {@inheritDoc}
     */
    public function getDateAdded()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateAdded', array());

        return parent::getDateAdded();
    }

    /**
     * {@inheritDoc}
     */
    public function save()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'save', array());

        return parent::save();
    }

    /**
     * {@inheritDoc}
     */
    public function delete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'delete', array());

        return parent::delete();
    }

    /**
     * {@inheritDoc}
     */
    public function remove()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'remove', array());

        return parent::remove();
    }

    /**
     * {@inheritDoc}
     */
    public function duplicate($newName, $newSKU = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'duplicate', array($newName, $newSKU));

        return parent::duplicate($newName, $newSKU);
    }

    /**
     * {@inheritDoc}
     */
    public function generatePage($templateID = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'generatePage', array($templateID));

        return parent::generatePage($templateID);
    }

    /**
     * {@inheritDoc}
     */
    public function setPageDescription($newDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPageDescription', array($newDescription));

        return parent::setPageDescription($newDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function setPageID($cID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPageID', array($cID));

        return parent::setPageID($cID);
    }

    /**
     * {@inheritDoc}
     */
    public function savePageID($cID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'savePageID', array($cID));

        return parent::savePageID($cID);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalSold()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalSold', array());

        return parent::getTotalSold();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttribute($ak, $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttribute', array($ak, $value));

        return parent::setAttribute($ak, $value);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttribute($ak, $displayMode = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttribute', array($ak, $displayMode));

        return parent::getAttribute($ak, $displayMode);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttributeValueObject($ak, $createIfNotFound = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttributeValueObject', array($ak, $createIfNotFound));

        return parent::getAttributeValueObject($ak, $createIfNotFound);
    }

}
