<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-05-09T01:56:26-05:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'timezone' => 'Asia/Dubai',
    'api_keys' => array(
        'google' => array(
            'maps' => 'AIzaSyCts22Yx6FP4tCgIbOhPezmmUPSeSU6cGI',
        ),
    ),
);
