<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-06-22T15:53:21+04:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      paypalCurrency
 * @group     community_store_paypal_standard
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'paypalEmail' => 'digitalmarketingducon-facilitator@gmail.com',
    'paypalTestMode' => '1',
    'paypalCurrency' => 'USD',
);
