<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-06-22T15:53:21+04:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      paymentInstructions
 * @group     community_store
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'productPublishTarget' => '166',
    'symbol' => 'AED',
    'whole' => '.',
    'thousand' => ',',
    'sizeUnit' => 'in',
    'weightUnit' => 'lb',
    'taxName' => '',
    'currency' => 'AED',
    'taxenabled' => null,
    'taxcountry' => null,
    'taxstate' => null,
    'taxcity' => '',
    'taxAddress' => '',
    'taxMatch' => '',
    'taxBased' => '',
    'taxrate' => '',
    'calculation' => 'add',
    'shippingenabled' => null,
    'shippingbase' => null,
    'shippingitem' => null,
    'deliveryInstructions' => null,
    'notificationemails' => 'sabinchacko03@gmail.com,sabinonweb@gmail.com,sabin.chacko@yahoo.in',
    'emailalerts' => 'sales@800benaa.com',
    'emailalertsname' => '800Benaa',
    'guestCheckout' => 'always',
    'shoppingDisabled' => '',
    'receiptHeader' => '<p style="text-align:center;font-size:18px;margin-bottom:10px;" rel="text-align:center;font-size:18px;padding-bottom:0px;"><strong><u>ORDER CONFIRMATION</u></strong><br><br></p>',
    'receiptFooter' => '<p data-redactor-inserted-image="true"><img id="image-marker" src="http://www.800benaa.com/download_file/view_inline/343" style="width: 100%;">
</p>',
    'invoiceMinimum' => '',
    'invoiceMaximum' => '',
    'paymentInstructions' => '<p>Checking the payment methods</p>',
);
