<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-08-06T13:16:56+04:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      csv.line_length
 * @group     community_store_import
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'import_file' => '6612',
    'max_execution_time' => '160',
    'default_image' => '0',
    'csv' => array(
        'delimiter' => ',',
        'enclosure' => '"',
        'line_length' => '1000',
    ),
);
