<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-08-06T12:54:22+04:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      mail.methods.smtp.encryption
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => '800Benaa',
    'version_installed' => '5.7.5.13',
    'maintenance_mode' => false,
    'misc' => array(
        'access_entity_updated' => 1489987106,
        'latest_version' => '8.2.1',
        'do_page_reindex_check' => false,
        'login_redirect' => 'PROFILE',
        'login_redirect_cid' => 0,
        'login_admin_to_dashboard' => 1,
        'user_timezones' => false,
    ),
    'cache' => array(
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'custom',
        'full_page_lifetime_value' => '10',
    ),
    'theme' => array(
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ),
    'seo' => array(
        'canonical_url' => '',
        'canonical_ssl_url' => '',
        'redirect_to_canonical_url' => 0,
        'url_rewriting' => 1,
        'tracking' => array(
            'code' => '<script>
  (function(i,s,o,g,r,a,m){i[\'GoogleAnalyticsObject\']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,\'script\',\'https://www.google-analytics.com/analytics.js\',\'ga\');

  ga(\'create\', \'UA-67543398-2\', \'auto\');
  ga(\'send\', \'pageview\');

</script>
<script type="text/javascript">
window.__lc = window.__lc || {};
window.__lc.license = 6516451;
(function() {
  var lc = document.createElement(\'script\'); lc.type = \'text/javascript\'; lc.async = true;
  lc.src = (\'https:\' == document.location.protocol ? \'https://\' : \'http://\') + \'cdn.livechatinc.com/tracking.js\';
  var s = document.getElementsByTagName(\'script\')[0]; s.parentNode.insertBefore(lc, s);
})();
</script>
<script type="text/javascript">
piAId = \'632421\';
piCId = \'11022\';
piHostname = \'pi.pardot.com\';

(function() {
	function async_load(){
		var s = document.createElement(\'script\'); s.type = \'text/javascript\';
		s.src = (\'https:\' == document.location.protocol ? \'https://pi\' : \'http://cdn\') + \'.pardot.com/pd.js\';
		var c = document.getElementsByTagName(\'script\')[0]; c.parentNode.insertBefore(s, c);
	}
	if(window.attachEvent) { window.attachEvent(\'onload\', async_load); }
	else { window.addEventListener(\'load\', async_load, false); }
})();
</script>

<!-- Facebook Pixel Code -->
<script>
  !function(f,b,e,v,n,t,s)
  {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};
  if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version=\'2.0\';
  n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];
  s.parentNode.insertBefore(t,s)}(window, document,\'script\',
  \'https://connect.facebook.net/en_US/fbevents.js\');
  fbq(\'init\', \'454837825313924\');
  fbq(\'track\', \'PageView\');
</script>
<noscript><img height="1" width="1" style="display:none"
  src="https://www.facebook.com/tr?id=454837825313924&ev=PageView&noscript=1"
/></noscript>
<!-- End Facebook Pixel Code -->',
            'code_position' => 'bottom',
        ),
    ),
    'accessibility' => array(
        'toolbar_titles' => true,
        'toolbar_large_font' => false,
        'display_help_system' => true,
    ),
    'mail' => array(
        'method' => 'smtp',
        'methods' => array(
            'smtp' => array(
                'server' => '800benaa.com',
                'username' => 'lead@800benaa.com',
                'password' => '@#utHI{biz2#',
                'port' => '587',
                'encryption' => 'TLS',
            ),
        ),
    ),
    'user' => array(
        'profiles_enabled' => false,
        'registration' => array(
            'email_registration' => false,
            'type' => 'validate_email',
            'captcha' => false,
            'enabled' => true,
            'validate_email' => true,
            'approval' => false,
            'notification' => '1',
            'notification_email' => 'marketing@800benaa.com',
        ),
        'gravatar' => array(
            'enabled' => false,
            'max_level' => 'g',
            'image_set' => '404',
        ),
    ),
    'api' => array(
        'secret' => '3ffce3ebb58048b2c23a368b1c476213979092efcebd8fb5441b6dd98639da76a40ee9883be0080b095836ebf5ebeb0300af9b114b4804b1f7e2893453a1256c',
    ),
);
