<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2020-06-22T15:53:21+04:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      networkStandardMode
 * @group     network_standard
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'networkID' => '2017565784656546',
    'networkTestMode' => '0',
    'networkCurrency' => 'AED',
    'networkMerchantID' => '201705171000003',
    'networkMerchantKey' => 'h6tbriQmcI4tMT3U50qHyJyBS2PGCoPqLolNfxlHNKE=',
    'networkStandardMode' => '1',
);
